version: "3"

services: 
  # TODO: add age-viewer as git submodule
  # age-viewer: # database ui
  #   build:
  #     context: ./dev/age-viewer/
  #     dockerfile: Dockerfile.AgeViewer
  #   image: rapsql/ageviewer:0.0.1
  #   container_name: ageviewer-container3
  #   ports:
  #     - "${AGEVIEWER_PORT}:3001"
  #   restart: unless-stopped

  swagger: # api ui
    container_name: swagger-container
    image: swaggerapi/swagger-ui:v4.15.2 # (!amd64 architecture only)
    ports:
      - "${SWAGGER_PORT}:8080"
    expose:
      - "${SWAGGER_PORT}"
    environment:
      API_URL: "${PGRST_OPENAPI_SERVER_PROXY_URI}"
      VALIDATOR_URL: "localhost"  # (!prevent invalid request intranet)
    restart: unless-stopped
    depends_on:
      - pgrst
    # networks:
    #   - rapsql-network

  pgrst: # database rest api
    container_name: pgrst-container
    image: postgrest/postgrest:v10.1.0
    ports:
      - "${PGRST_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://${PGRST_USER}:${PGRST_PASSWORD}@rapsqldb:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_OPENAPI_SERVER_PROXY_URI: ${PGRST_OPENAPI_SERVER_PROXY_URI}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_OPENAPI_SECURITY_ACTIVE: ${PGRST_OPENAPI_SECURITY_ACTIVE}
      # PGRST_DB_PRE_REQUEST: ${PGRST_DB_PRE_REQUEST} # (!unused see .env)
    restart: unless-stopped
    depends_on:
      - rapsqldb
    # networks:
    #   - rapsql-network

  rapsqldb: # enhanced postgresql database
    build:
      context: .
      dockerfile: Dockerfile
    image: rapsql/pg-age-pljava:v0.1.0
    container_name: rapsqldb-container
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - rapsqldata:/var/lib/postgresql/data
    restart: unless-stopped
    # networks:
    #   - rapsql-network

volumes:
  rapsqldata: {}

# networks:
#   rapsql-network:
#     name: rapsql-network
#     driver: bridge
