# 1 Get the base image
FROM python:3.8.10-alpine

# 2 Copy the current directory contents into the container at /app
COPY . /app

# 3 Set the working directory to /app
WORKDIR /app

# 4 Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run test_api.py when the container launches
CMD ["python", "-m", "pytest", "api_test.py"]
