name: Build RAPSQL Container Image

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: cp .env.example .env

      - name: Run Test-DB Dependency Container
        run: docker compose -f ${{ github.workspace }}/test/db/docker-compose.yml up -d

      - name: Build RAPSQL Container Image
        run: docker compose build

      - name: Destroy Test-DB Dependency Conainer
        run: docker compose -f ${{ github.workspace }}/test/db/docker-compose.yml down -v

      - name: Deploy RAPSQL Containers
        run: |
          docker compose up -d
          sleep 20
          timeout 60s bash -c 'until curl -sSf http://pgrst-container:3000 >/dev/null; do sleep 5; done'

      - name: Build RAPSQL API Test Container Image
        run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml build --no-cache

      - name: Deploy RAPSQL API Test Container
        run: |
          docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml up
        
      - name: Destroy RAPSQL API Test Container
        run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml down
        
      - name: Destroy RAPSQL Containers
        run: docker compose down -v
