name: Build RAPSQL Container Image

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Deploy Test-DB dependencies
        run: docker compose -f docker-compose.testdb.yml up -d

