name: Test RAPSQL API

on:
  push:
    branches:
      - cicd

jobs:
  api-testing-workflow:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment
        run: cp .env.example .env

      - name: Build RAPSQL Image
        run: docker compose build 

      - name: Provide RAPSQL Service
        run: |
          docker compose up -d
          sleep 20

      - name: Transpiler Integration Test
        run: |
          docker exec rapsqldb-container sh -c \
          "cd tmp/s2agec && mvn test \
          -Dtest=TranspilerTest"

      - name: API Test internal
        run: |
          docker exec rapsqldb-container sh -c \
          "cd tmp/s2agec && mvn test \
          -Dtest=ApiTest -Dapi.url=http://pgrst-container:3000"

      - name: API Test external Container
        run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml up --build

      - name: Destroy RAPSQL API Test Container
        run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml down
      
      - name: Destroy RAPSQL Service
        run: docker compose down -v


