name: Build RAPSQL Container Image

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Test-DB dependencies
        run: docker compose -f docker-compose.testdb.yml up -d

