name: Build RAPSQL Container Image

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: cp .env.example .env

      - name: Deploy Test-DB Dependency
        run: docker compose -f docker-compose.testdb.yml up -d

      - name: Build RAPSQL Container Image
        run: docker compose build

      - name: Destroy Test-DB Dependency
        run: docker compose -f docker-compose.testdb.yml down -v
